### ISSUE TITLE
Very impressive!

### ISSUE THREAD

**Issue by marilirulita** [VanessaAoki/secret-shop#3]
I just suggest your project could allow any member to add new articles, not just the admin.

**Comment by vichuge** [comment]
Hi, @VanessaAoki  your project looks so nice to me! In part, because it just appears some videogames that I have played or actually play 😄 

I just find an important issue to will improve your live demo and the future people to enter there

- I just note that some images don't appear on the page, being more specific, the main image for each article. I just try to find a way to solve it but I couldn't find it, I'm sorry 😢 
![image](https://user-images.githubusercontent.com/20563252/121205154-0c4f0e80-c83d-11eb-938a-2b6cf0ecb850.png)

Thanks for your time to read this and if I can help, I'll be happy to do it 😃

**Comment by VanessaAoki** [comment]
Thanks guys! I'm working to fix both issues!
